### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by MonsieurBon**

### CODE REVIEW

**Comment by hiddenalpha** [comment]
(*trivial*) Maybe it would be worth fetching a few more (like somewhat in range 10-100) to cover other edge cases as well. 10-100 should't hurt at all IMHO.

**Review by hiddenalpha — APPROVED** [review]

**Review by hiddenalpha — COMMENTED** [review]
Why do we change the pom version again?

**Comment by MonsieurBon** [comment]
> Why do we change the pom version again?

Normally the commits from the release on the master are merged back to develop after the release. This failed here https://github.com/swisspost/apikana-java/actions/runs/8006164501 Therefore I'm merging these commits manually in this PR

**Comment by MonsieurBon** [comment]
> (_trivial_) Maybe it would be worth fetching a few more (like somewhat in range 10-100) to cover other edge cases as well. 10-100 should't hurt at all IMHO.

I was thinking about this as well. But we actually only need enough so that develop and master have a common ancestor and so git knows what to merge.

**Review by hiddenalpha — APPROVED** [review]

**Pull request merged**
